services:
  app:
    image: ${JUSTIFICACION_IMAGE}
    container_name: justificacion-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${JUSTIFICACION_PORT}:8082"
      - "${JUSTIFICACION_ACTUATOR_PORT}:8083"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JPA_DDL=${JPA_DDL}
      - DB_HOST=${DB_HOST}
      - PORT=8082
    networks:
      - justificacion-network

  db:
    image: ${DB_IMAGE}
    container_name: justificacion-postgres
    restart: unless-stopped
    ports:
      - "${DB_HOST_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - justificacion-network

networks:
  justificacion-network:
    driver: bridge