services:
  usuarioservice:
    build: ./MicroservicioUsuario
    image: ${USUARIO_IMAGE}
    container_name: usuarioservice
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "${USUARIO_PORT}:8080"
      - "${USUARIO_ACTUATOR_PORT}:8081"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JPA_DDL=${JPA_DDL}
      - DB_HOST=jdbc:postgresql://db:5432/${DB_NAME}
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECURITY_URL=http://seguridad-service:8085
      - INTERNAL_SECRET=${INTERNAL_SECRET}
    networks:
      - mynetwork

  asistenciaservice:
    build: ./MicroservicioAsistencia
    image: ${ASISTENCIA_IMAGE}
    container_name: asistencia-app
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "${ASISTENCIA_PORT}:8081"
      - "${ASISTENCIA_ACTUATOR_PORT}:8082"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JPA_DDL=${JPA_DDL}
      - DB_HOST=jdbc:postgresql://db:5432/${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECURITY_URL=http://seguridad-service:8085
      - INTERNAL_SECRET=${INTERNAL_SECRET}
    networks:
      - mynetwork

  planilla-service:
    build: ./MicroservicioPlanilla
    image: ${PLANILLA_IMAGE}
    container_name: planilla-service
    restart: always
    ports:
      - "${PLANILLA_PORT}:8080"
      - "${PLANILLA_PORT_ACTUATOR}:8081"
    depends_on:
      - db
      - redis
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=jdbc:postgresql://db:5432/${DB_NAME}
      - JPA_DDL=${JPA_DDL}
      - PORT=8080
      - PLANILLA_PORT_ACTUATOR=${PLANILLA_PORT_ACTUATOR}
      - HOMOMORPHIC_A_SETS=${HOMOMORPHIC_A_SETS}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECURITY_URL=http://seguridad-service:8085
      - INTERNAL_SECRET=${INTERNAL_SECRET}
    networks:
      - mynetwork

  reporte-service:
    build: ./MicroservicioReporte
    image: ${REPORTE_IMAGE}
    container_name: reporte-service
    restart: always
    ports:
      - "${REPORTE_PORT}:8080"
      - "${REPORTE_PORT_ACTUATOR}:8081"
    depends_on:
      - db
      - redis
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=jdbc:postgresql://db:5432/${DB_NAME}
      - JPA_DDL=${JPA_DDL}
      - PORT=8080
      - REPORTE_PORT_ACTUATOR=${REPORTE_PORT_ACTUATOR}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECURITY_URL=http://seguridad-service:8085
      - INTERNAL_SECRET=${INTERNAL_SECRET}
    networks:
      - mynetwork

  justificacion-service:
    build: ./MicroServicioJustificacion
    image: ${JUSTIFICACION_IMAGE}
    container_name: justificacion-service
    restart: always
    ports:
      - "${JUSTIFICACION_PORT}:8080"
      - "${JUSTIFICACION_PORT_ACTUATOR}:8081"
    depends_on:
      - db
      - redis
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=jdbc:postgresql://db:5432/${DB_NAME}
      - JPA_DDL=${JPA_DDL}
      - PORT=8080
      - JUSTIFICACION_PORT_ACTUATOR=${JUSTIFICACION_PORT_ACTUATOR}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECURITY_URL=http://seguridad-service:8085
      - INTERNAL_SECRET=${INTERNAL_SECRET}
    networks:
      - mynetwork

  db:
    image: ${DB_IMAGE}
    container_name: db
    restart: unless-stopped
    ports:
      - "${DB_HOST_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - mynetwork

  redis:
    image: redis:alpine
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  seguridad-service:
    build: ./MicroServicioSeguridad
    image: ${SEGURIDAD_IMAGE}
    container_name: seguridad-service
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - "${SEGURIDAD_PORT}:8085"
    environment:
      - PORT=8085
      - DB_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - MASTER_KEY_E=${MASTER_KEY_E}
      - MASTER_KEY_N=${MASTER_KEY_N}
      - MASTER_KEY_D=${MASTER_KEY_D}
      - INTERNAL_SECRET=${INTERNAL_SECRET}
      - JWT_SECRET_KEY=${SECRET_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
