# Nombre de la aplicacion
spring.application.name=MicroservicioAsistencia
app.version=0.1.0
app.api.version=v1
server.port=8081

# Management
management.server.port=8082
management.endpoints.web.exposure.include=*

# Configuracion de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/asistencia_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuracion adicional
spring.main.allow-circular-references=true

# Configuracion de HikariCP (pool de conexiones)
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-test-query=SELECT 1

# Logging
logging.level.org.springframework=ERROR
logging.level.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.root=ERROR
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.hibernate=ERROR
