spring.application.name=MicroservicioPlanilla
app.version=1.0.0
app.api.version=v1

server.port=8080

management.server.port=8081
management.endpoints.web.exposure.include=*

# ? IMPORTANTE: usar nombre del servicio docker (NO localhost)
spring.datasource.url=jdbc:postgresql://postgres:5432/planilla_db
spring.datasource.username=devdb
spring.datasource.password=a1b2c3d4
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.main.allow-circular-references=true

# ? Hikari (opcional pero recomendado)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.minimum-idle=5

# ? Para evitar errores al iniciar con Docker
spring.datasource.hikari.initialization-fail-timeout=60000

# ? Logs
logging.level.org.springframework=ERROR
logging.level.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.root=ERROR
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.hibernate=ERROR