version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: planilla_db
      POSTGRES_USER: devdb
      POSTGRES_PASSWORD: a1b2c3d4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  planilla-service:
    build: .   # 👈 AQUÍ hace build automático con tu Dockerfile
    container_name: planilla-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: