server:
  port: ${PORT:8085}

spring:
  application:
    name: MicroServicioSeguridad
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/asis_track_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

app:
  security:
    master-key-e: ${MASTER_KEY_E:65537}
    master-key-n: ${MASTER_KEY_N:12345678901234567890}
    master-key-d: ${MASTER_KEY_D:98765432109876543210}
    internal-secret: ${INTERNAL_SECRET:microservice-internal-secret}
    rotation-delay: ${ROTATION_DELAY:604800000}
    jwt:
      secrect-key: ${JWT_SECRET_KEY:ThisIsAVeryLongSecretKeyDefinedForJWTAuthenticationToWorkBecauseItNeedsToBeVeryLong}
