name: Build APK

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./front_asis_track

jobs:
  build-apk:
    runs-on: ubuntu-latest
    environment: Flutter

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: stable

      - run: flutter pub get

      - run: flutter build apk --release --build-number=${{ github.run_number }} --dart-define=API_BASE_URL=${{ secrets.API_BASE_URL }}

      - name: Subir APK como artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ./front_asis_track/build/app/outputs/flutter-apk/app-release.apk
