name: Deploy Flutter Web to Firebase

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./front_asis_track

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Flutter

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: stable

      - name: Instalar dependencias Flutter
        run: flutter pub get

      - name: Compilar Flutter Web
        run: flutter build web --release

      - name: Generar env-config.js
        run: |
          cat <<EOF > build/web/env-config.js
          window.env = {
            API_BASE_URL: "${{ secrets.API_BASE_URL }}"
          };
          EOF

      - name: Desplegar en Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: asistrack-60b80
          entryPoint: ./front_asis_track
